tap "coursier/formulas"
tap "federico-terzi/espanso"
tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "readline"
brew "autojump"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bat"
brew "carthage"
brew "circleci"
brew "cmigemo"
brew "cocoapods"
brew "colordiff"
brew "direnv"
brew "dog"
brew "duf"
brew "dust"
brew "fd"
brew "figlet"
brew "firebase-cli"
brew "git"
brew "git-secrets"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "grep"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "kotlin"
brew "ktlint"
brew "mas"
brew "mint"
brew "mysql", restart_service: true
brew "ncdu"
brew "nkf"
brew "node-build"
brew "nodenv"
brew "oath-toolkit"
brew "percol"
brew "plantuml"
brew "postgresql", restart_service: true
brew "pwgen"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "sd"
brew "shellcheck"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "coursier/formulas/coursier"
brew "federico-terzi/espanso/espanso"
brew "getsentry/tools/sentry-cli"
cask "alfred"
cask "android-ndk"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "bartender"
cask "discord"
cask "docker"
cask "dropbox"
cask "emacs"
cask "font-hackgen"
cask "google-chrome"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "lastfm"
cask "macdown"
cask "pastebot"
cask "rectangle"
cask "slack"
cask "tweetbot"
mas "1Password", id: 443987910
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "TweetDeck", id: 485812721
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
