(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons-completion-mode t)
 '(all-the-icons-dired-monochrome nil)
 '(all-the-icons-scale-factor 1.0)
 '(anzu-mode-lighter "")
 '(anzu-replace-to-string-separator " => ")
 '(anzu-use-migemo t)
 '(backup-inhibited t t)
 '(centaur-tabs-cycle-scope 'tabs)
 '(centaur-tabs-left-edge-margin "")
 '(centaur-tabs-modified-marker "*")
 '(centaur-tabs-right-edge-margin "")
 '(centaur-tabs-set-close-button nil)
 '(centaur-tabs-set-icons t)
 '(centaur-tabs-set-modified-marker t)
 '(centaur-tabs-show-count t)
 '(centaur-tabs-show-navigation-buttons t)
 '(centaur-tabs-show-new-tab-button nil)
 '(column-number-mode t)
 '(company-require-match 'never)
 '(company-selection-wrap-around t)
 '(company-statistics-mode t)
 '(company-tooltip-align-annotations t)
 '(company-transformers
   '(company-sort-by-statistics company-sort-by-backend-importance))
 '(completion-styles '(orderless))
 '(consult-preview-key 'any)
 '(create-lockfiles nil)
 '(css-indent-offset 2)
 '(cua-enable-cua-keys nil)
 '(cua-mode t)
 '(delete-auto-save-files t)
 '(diredp-hide-details-initially-flag nil)
 '(diredp-hide-details-propagate-flag nil)
 '(direnv-always-show-summary nil)
 '(direnv-mode t)
 '(enh-ruby-deep-indent-paren nil)
 '(flycheck-display-errors-delay 0.5)
 '(flycheck-posframe-position 'window-bottom-right-corner)
 '(git-gutter:update-interval 5)
 '(global-anzu-mode t)
 '(global-auto-revert-mode t)
 '(global-company-mode t)
 '(global-flycheck-mode t)
 '(global-git-gutter-mode t)
 '(global-undo-tree-mode t)
 '(gud-key-prefix "")
 '(highlight-indent-guides-delay 0)
 '(highlight-indent-guides-responsive 'top)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-frame-alist '((width . 160) (height . 40)))
 '(initial-scratch-message nil)
 '(js-indent-level 2)
 '(js2-strict-missing-semi-warning nil)
 '(kill-ring-max 10000)
 '(kill-whole-line t)
 '(line-number-mode t)
 '(lsp-disabled-clients '(deno-ls))
 '(lsp-enable-indentation nil)
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-typescript-server "ts-ls")
 '(lsp-ui-doc-position 'at-point)
 '(magit-delta-default-dark-theme "Kabukicho")
 '(make-backup-files nil)
 '(marginalia-mode t)
 '(markdown-toc-indentation-space 2)
 '(menu-bar-mode t)
 '(migemo-command
   (cl-find-if 'executable-find
               '("/opt/homebrew/bin/cmigemo" "/usr/local/bin/cmigemo")))
 '(migemo-dictionary
   (cl-find-if 'file-exists-p
               '("/opt/homebrew/share/migemo/utf-8/migemo-dict" "/usr/local/share/migemo/utf-8/migemo-dict" "/usr/share/cmigemo/utf-8/migemo-dict")))
 '(migemo-isearch-min-length 2)
 '(migemo-regex-dictionary nil)
 '(migemo-user-dictionary nil)
 '(neo-default-system-application "open")
 '(neo-mode-line-type 'none)
 '(neo-theme 'icons)
 '(neo-vc-integration '(face char))
 '(neo-window-fixed-size nil)
 '(neo-window-width 30)
 '(nyan-minimum-window-width 96)
 '(nyan-mode t)
 '(plantuml-default-exec-mode 'executable)
 '(plantuml-executable-path
   (cl-find-if 'executable-find
               '("/opt/homebrew/bin/plantuml" "/usr/local/bin/plantuml")))
 '(plantuml-indent-level 2)
 '(plantuml-output-type "svg" t)
 '(popwin-mode t)
 '(powerline-default-separator 'utf-8)
 '(powerline-display-hud nil)
 '(powerline-display-mule-info nil)
 '(recentf-auto-cleanup 'never)
 '(recentf-max-menu-items 100000)
 '(recentf-max-saved-items 100000)
 '(recentf-mode t)
 '(require-final-newline t)
 '(ring-bell-function 'ignore)
 '(ruby-deep-indent-paren nil)
 '(ruby-use-smie nil t)
 '(savehist-mode t)
 '(savekill-max-saved-items 1000)
 '(scroll-bar-mode nil)
 '(scss-compile-at-save nil)
 '(show-paren-delay 0)
 '(show-paren-mode t)
 '(show-paren-style 'mixed)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(treemacs-indentation 1)
 '(treemacs-space-between-root-nodes nil)
 '(treemacs-user-mode-line-format 'none)
 '(truncate-lines t)
 '(typescript-indent-level 2)
 '(undo-tree-auto-save-history nil)
 '(undohist-ignored-files '("^magit" "COMMIT_EDITMSG\\'"))
 '(uniquify-ignore-buffers-re "*[^*]+*")
 '(vc-follow-symlinks t)
 '(vertico-count 20)
 '(vertico-mode t)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-part-padding 0)
 '(web-mode-script-padding 0)
 '(web-mode-style-padding 0)
 '(wgrep-auto-save-buffer t)
 '(which-key-mode t)
 '(which-key-posframe-mode t)
 '(xref-show-definitions-function 'consult-xref)
 '(xref-show-xrefs-function 'consult-xref))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(flycheck-posframe-face ((t (:inherit default :background "#464752" :box (:line-width (1 . 1) :color "#464752" :style flat-button)))))
 '(treemacs-all-the-icons-root-face ((t (:inherit font-lock-string-face))))
 '(treemacs-root-face ((t (:inherit font-lock-keyword-face :underline t :height 1.0)))))
